MODEL:
  TYPE: "interactron"
  WEIGHTS: "pretrained_weights/detr-dc5-backbone.pth"
  NUM_CLASSES: 1235
  BACKBONE: "resnet50"
  SET_COST_CLASS: 1.0
  SET_COST_BBOX: 5.0
  SET_COST_GIOU: 2.0
  TEST_RESOLUTION: 300
  PREDICT_ACTIONS: True
  NUM_LAYERS: 8
  NUM_HEADS: 8
  EMBEDDING_DIM: 256
  BLOCK_SIZE: 2060
  IMG_FEATURE_SIZE: 256
  OUTPUT_SIZE: 256
  BOX_EMB_SIZE: 256
  EMBEDDING_PDROP: 0.1
  RESIDUAL_PDROP: 0.1
  ATTENTION_PDROP: 0.1
DATASET:
  TRAIN:
    TYPE: "sequence"
    MODE: "train"
    ANNOTATION_ROOT: "data/interactron/annotations/interactron_v1_train.json"
    IMAGE_ROOT: "data/interactron/train"
  TEST:
    TYPE: "sequence"
    MODE: "test"
    ANNOTATION_ROOT: "data/interactron/annotations/interactron_v1_val.json"
    IMAGE_ROOT: "data/interactron/val"
TRAINER:
  TYPE: "interactron"
  BATCH_SIZE: 16
  NUM_WORKERS: 16
  MAX_EPOCHS: 2000
  LEARNING_RATE: 1e-4
  BETA1: 0.9
  BETA2: 0.95
  MOMENTUM: 0.9
  GRAD_NORM_CLIP: 1.0
  WEIGHT_DECAY: 0.0
  OPTIM_TYPE: "AdamW"
  LR_DECAY: False
  WARMUP_TOKENS: 0
  FINAL_TOKENS: 0 # 2.5e7
  OUTPUT_DIRECTORY: "training_results/interactron"
EVALUATOR:
  TYPE: "interactive_evaluator"
  BATCH_SIZE: 1
  NUM_WORKERS: 1
  OUTPUT_DIRECTORY: "evaluation_results/interactron"
  CHECKPOINT: "pretrained_weights/interactron.pth"
