MODEL:
  TYPE: "interactron_random"
  WEIGHTS: "pretrained_weights/detr-dc5-backbone.pth"
  NUM_CLASSES: 1235
  BACKBONE: "resnet50"
  SET_COST_CLASS: 1.0
  SET_COST_BBOX: 5.0
  SET_COST_GIOU: 2.0
  TEST_RESOLUTION: 300
  PREDICT_ACTIONS: False
  NUM_LAYERS: 2
  NUM_HEADS: 2
  EMBEDDING_DIM: 256
  BLOCK_SIZE: 2060
  IMG_FEATURE_SIZE: 256
  OUTPUT_SIZE: 256
  BOX_EMB_SIZE: 256
  EMBEDDING_PDROP: 0.1
  RESIDUAL_PDROP: 0.1
  ATTENTION_PDROP: 0.1
DATASET:
  TRAIN:
    TYPE: "sequence"
    MODE: "train"
    ANNOTATION_ROOT: "data/interactron/annotations/interactron_v1_train-full.json"
    IMAGE_ROOT: "data/interactron/train-full"
  TEST:
    TYPE: "sequence"
    MODE: "test"
    ANNOTATION_ROOT: "data/interactron/annotations/interactron_v1_val-procthor.json"
    IMAGE_ROOT: "data/interactron/val-procthor"
TRAINER:
  TYPE: "interactron_random"
  BATCH_SIZE: 16
  NUM_WORKERS: 16
  MAX_EPOCHS: 2000
  LEARNING_RATE: 1e-4
  BETA1: 0.9
  BETA2: 0.95
  MOMENTUM: 0.9
  GRAD_NORM_CLIP: 1.0
  WEIGHT_DECAY: 0.1
  OPTIM_TYPE: "AdamW"
  LR_DECAY: False
  WARMUP_TOKENS: 0
  FINAL_TOKENS: 0 # 2.5e7
  OUTPUT_DIRECTORY: "training_results/interactron_random"
EVALUATOR:
  # TYPE: "every_path_evaluator"
  TYPE: "random_policy_evaluator"
  BATCH_SIZE: 1
  NUM_WORKERS: 1
  OUTPUT_DIRECTORY: "evaluation_results/interactron_random"
  CHECKPOINT: "training_results/interactron_random/joined.pt"
  # CHECKPOINT: "pretrained_weights/interactron_random_53.pt"
  # CHECKPOINT: "pretrained_weights/interactron-rand.pth"
